// <auto-generated />
using System;
using FurnitureBuildingSolution.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FurnitureBuildingSolution.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190329084444_AddedBookcaseTables")]
    partial class AddedBookcaseTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbBookcase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Bookcases");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbCompartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BottomId");

                    b.Property<int?>("DbBookcaseId");

                    b.Property<int?>("LeftId");

                    b.Property<int?>("RightId");

                    b.Property<int?>("TopId");

                    b.HasKey("Id");

                    b.HasIndex("BottomId");

                    b.HasIndex("DbBookcaseId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.HasIndex("TopId");

                    b.ToTable("Compartments");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DbBookcaseId");

                    b.Property<int>("EndXCoordinate");

                    b.Property<int>("EndYCoordinate");

                    b.Property<bool>("InnerPlate");

                    b.Property<int>("StartXCoordinate");

                    b.Property<int>("StartYCoordinate");

                    b.HasKey("Id");

                    b.HasIndex("DbBookcaseId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbCompartment", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbPlate", "Bottom")
                        .WithMany()
                        .HasForeignKey("BottomId");

                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbBookcase")
                        .WithMany("Compartments")
                        .HasForeignKey("DbBookcaseId");

                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbPlate", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbPlate", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbPlate", "Top")
                        .WithMany()
                        .HasForeignKey("TopId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.DatabaseEntities.DbPlate", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.DatabaseEntities.DbBookcase")
                        .WithMany("Plates")
                        .HasForeignKey("DbBookcaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
