// <auto-generated />
using System;
using FurnitureBuildingSolution.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FurnitureBuildingSolution.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190413095208_DraggablePropertyOnPlates")]
    partial class DraggablePropertyOnPlates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbBookcase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookcases");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbCompartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BottomId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DbBookcaseId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<bool>("HasDoor");

                    b.Property<bool>("HasDrawer");

                    b.Property<int?>("LeftId");

                    b.Property<string>("Model");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("RightId");

                    b.Property<int?>("TopId");

                    b.HasKey("Id");

                    b.HasIndex("BottomId");

                    b.HasIndex("DbBookcaseId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.HasIndex("TopId");

                    b.ToTable("Compartments");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DbBookcaseId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<bool>("Draggable");

                    b.Property<int>("EndXCoordinate");

                    b.Property<int>("EndYCoordinate");

                    b.Property<bool>("InnerPlate");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("StartXCoordinate");

                    b.Property<int>("StartYCoordinate");

                    b.HasKey("Id");

                    b.HasIndex("DbBookcaseId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbBookcase", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbCompartment", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Bottom")
                        .WithMany()
                        .HasForeignKey("BottomId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase")
                        .WithMany("Compartments")
                        .HasForeignKey("DbBookcaseId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Top")
                        .WithMany()
                        .HasForeignKey("TopId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbPlate", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase")
                        .WithMany("Plates")
                        .HasForeignKey("DbBookcaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
