// <auto-generated />
using System;
using FurnitureBuildingSolution.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FurnitureBuildingSolution.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200824115020_AddedGuestCheckout")]
    partial class AddedGuestCheckout
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressString");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("DawaId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbBookcase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BaseHeight");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<int>("DoorMaterial");

                    b.Property<bool>("IsWallSuspended");

                    b.Property<bool>("LockedForEditing");

                    b.Property<int?>("MaterialId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<int>("PlateDepth");

                    b.Property<double?>("PriceIndex");

                    b.Property<double?>("SkirtingBoardDepth");

                    b.Property<double?>("SkirtingBoardHeight");

                    b.Property<double?>("StartingPrice");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookcases");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbCompartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BackPlatePosition");

                    b.Property<int?>("BottomId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DbBookcaseId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<int>("DoorPosition");

                    b.Property<int>("ForceSupport");

                    b.Property<bool>("HasDoor");

                    b.Property<bool>("HasDrawer");

                    b.Property<int?>("LeftId");

                    b.Property<string>("Model");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("RightId");

                    b.Property<int?>("TopId");

                    b.HasKey("Id");

                    b.HasIndex("BottomId");

                    b.HasIndex("DbBookcaseId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.HasIndex("TopId");

                    b.ToTable("Compartments");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<int>("FailedSendAttempts");

                    b.Property<string>("HtmlBody");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Receiver");

                    b.Property<DateTime?>("Sent");

                    b.Property<string>("Subject");

                    b.Property<string>("TextBody");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<int>("ListPosition");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("PricePerSquareMeter");

                    b.Property<string>("SideTextureLocation")
                        .IsRequired();

                    b.Property<string>("SurfaceTextureLocation")
                        .IsRequired();

                    b.Property<double>("Thickness");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("OrderNumber");

                    b.Property<int>("OrderStatus");

                    b.Property<DateTime>("OrderTime");

                    b.Property<int?>("ShippingAddressId");

                    b.Property<int?>("UserId");

                    b.Property<string>("VatNumber");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookcaseId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DbOrderId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("Quantity");

                    b.Property<int>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("BookcaseId");

                    b.HasIndex("DbOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DbBookcaseId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<bool>("Draggable");

                    b.Property<int>("EndXCoordinate");

                    b.Property<int>("EndYCoordinate");

                    b.Property<bool>("InnerPlateEnd");

                    b.Property<bool>("InnerPlateStart");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("ParentCompartmentId");

                    b.Property<int?>("SpecialDepth");

                    b.Property<int>("StartXCoordinate");

                    b.Property<int>("StartYCoordinate");

                    b.HasKey("Id");

                    b.HasIndex("DbBookcaseId");

                    b.HasIndex("ParentCompartmentId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbStandardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookcaseId");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("ImageFilename");

                    b.Property<string>("Material");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProductCategoryId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BookcaseId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("StandardModels");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<Guid?>("PasswordRecoveryKey");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbBookcase", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbMaterial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbCompartment", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Bottom")
                        .WithMany()
                        .HasForeignKey("BottomId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase")
                        .WithMany("Compartments")
                        .HasForeignKey("DbBookcaseId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbPlate", "Top")
                        .WithMany()
                        .HasForeignKey("TopId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbOrder", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbOrderItem", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase", "Bookcase")
                        .WithMany()
                        .HasForeignKey("BookcaseId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("DbOrderId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbPlate", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase")
                        .WithMany("Plates")
                        .HasForeignKey("DbBookcaseId");

                    b.HasOne("FurnitureBuildingSolution.Database.DbCompartment", "ParentCompartment")
                        .WithMany("InternalPlates")
                        .HasForeignKey("ParentCompartmentId");
                });

            modelBuilder.Entity("FurnitureBuildingSolution.Database.DbStandardModel", b =>
                {
                    b.HasOne("FurnitureBuildingSolution.Database.DbBookcase", "Bookcase")
                        .WithMany()
                        .HasForeignKey("BookcaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FurnitureBuildingSolution.Database.DbProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
